services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "4000:4000"
    environment:
      - DATABASE_URL=mongodb+srv://gattupalligvg_db_user:KzJuCirrNyngcs0i@cluster0.frzsxfl.mongodb.net/?appName=Cluster0
      - NODE_ENV=production
    restart: always

  frontend:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - backend
    restart: always
